module.exports = [
  {
    pic:
      'https://imgservice.suning.cn/uimg1/b2c/image/PsUqOk27kiOaK-Dv976m1A.jpg',
  },
  {
    pic:
      'https://imgservice.suning.cn/uimg1/b2c/image/4RHKQt85txGKJuAAJzbykQ.jpg',
  },
  {
    pic:
      'https://imgservice.suning.cn/uimg1/b2c/atmosphere/GORakIgCRs--n3Dsw0kBcw.jpg',
  },
  {
    pic:
      'https://imgservice.suning.cn/uimg1/b2c/image/G3C28ACESkiBE4jMhbjE_w.jpg',
  },
  {
    pic:
      'https://imgservice.suning.cn/uimg1/b2c/atmosphere/by3KjcuJCydUP78bz2q5Vw.jpg',
  },
  {
    pic:
      'https://imgservice.suning.cn/uimg1/b2c/image/PsUqOk27kiOaK-Dv976m1A.jpg',
  },
  {
    pic:
      'https://imgservice.suning.cn/uimg1/b2c/image/4RHKQt85txGKJuAAJzbykQ.jpg',
  },
  {
    pic:
      'https://imgservice.suning.cn/uimg1/b2c/atmosphere/GORakIgCRs--n3Dsw0kBcw.jpg',
  },
  {
    pic:
      'https://imgservice.suning.cn/uimg1/b2c/image/G3C28ACESkiBE4jMhbjE_w.jpg',
  },
  {
    pic:
      'https://imgservice.suning.cn/uimg1/b2c/atmosphere/by3KjcuJCydUP78bz2q5Vw.jpg',
  },
];
